# -*- coding: utf-8 -*-
"""Lat_long_feature_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A7kEuiTNZpM2vvguJY0NkAf-OabqskJ8
"""



"""# Find cordinates"""

"""
Fetch Singapore location data from OpenStreetMap via the Overpass API.
Retrieves MRT/LRT stations, shopping malls, bus stations/interchanges,
hawker centres, and schools, saving each to a separate CSV file.

No API key required.
"""

import requests
import pandas as pd
import time


# Changi Airport Skytrain station names (private APM, not public MRT/LRT)
CHANGI_SKYTRAIN_STATIONS = {"a", "a south", "b", "c", "d", "e", "f"}

# Sentosa Express station names (tourist monorail, not public MRT/LRT)
SENTOSA_EXPRESS_STATIONS = {
    "beach station",
    "waterfront station",
    "imbiah station",
    "resorts world station",
}


def query_overpass(query: str, timeout: int = 90) -> list:
    """
    Execute an Overpass API query and return the elements.

    Parameters
    ----------
    query : str
        The Overpass QL query
    timeout : int
        Request timeout in seconds

    Returns
    -------
    list of dict
        Elements from the Overpass API response
    """
    overpass_url = "https://overpass-api.de/api/interpreter"

    try:
        resp = requests.post(overpass_url, data={"data": query}, timeout=timeout)
        resp.raise_for_status()
        return resp.json().get("elements", [])
    except Exception as e:
        print(f"Error querying Overpass API: {e}")
        return []


def get_coordinates(element: dict) -> tuple:
    """
    Extract lat/lon from an OSM element (node, way, or relation).

    Parameters
    ----------
    element : dict
        OSM element from Overpass API

    Returns
    -------
    tuple (lat, lon) or (None, None) if not found
    """
    if element["type"] == "node":
        return element.get("lat"), element.get("lon")
    else:
        center = element.get("center", {})
        return center.get("lat"), center.get("lon")


def get_mrt_stations() -> pd.DataFrame:
    """
    Query OpenStreetMap for all public MRT/LRT stations in Singapore.
    Excludes private systems (Changi Skytrain, Sentosa Express).

    Returns
    -------
    pd.DataFrame with columns: station_name, lat, long
    """
    print("Fetching MRT/LRT stations...")

    query = """
    [out:json][timeout:60];
    area["ISO3166-1"="SG"]->.sg;
    (
      node["railway"="station"]["station"~"subway|light_rail|monorail"](area.sg);
      way ["railway"="station"]["station"~"subway|light_rail|monorail"](area.sg);
      rel ["railway"="station"]["station"~"subway|light_rail|monorail"](area.sg);
    );
    out center;
    """

    elements = query_overpass(query)
    rows = []

    for el in elements:
        tags = el.get("tags", {})
        name = tags.get("name", "Unknown")
        name_lower = name.strip().lower()
        operator = tags.get("operator", "").lower()
        network = tags.get("network", "").lower()

        # Skip entrance/exit nodes
        if tags.get("entrance") or tags.get("railway") == "subway_entrance":
            continue
        if name_lower.startswith("exit"):
            continue

        # Skip Changi Airport Skytrain
        if "changi" in operator or "changi" in network:
            continue
        if name_lower in CHANGI_SKYTRAIN_STATIONS:
            continue

        # Skip Sentosa Express
        if "sentosa" in operator or "sentosa" in network:
            continue
        if name_lower in SENTOSA_EXPRESS_STATIONS:
            continue

        lat, lon = get_coordinates(el)
        if lat and lon:
            rows.append({"station_name": name, "lat": lat, "long": lon})

    if not rows:
        print("Warning: No MRT/LRT stations found")
        return pd.DataFrame(columns=["station_name", "lat", "long"])

    df = (pd.DataFrame(rows)
          .drop_duplicates("station_name")
          .sort_values("station_name")
          .reset_index(drop=True))

    print(f"Found {len(df)} MRT/LRT stations")
    return df


def get_shopping_malls() -> pd.DataFrame:
    """
    Query OpenStreetMap for shopping malls in Singapore.

    Returns
    -------
    pd.DataFrame with columns: mall_name, lat, long
    """
    print("Fetching shopping malls...")

    query = """
    [out:json][timeout:60];
    area["ISO3166-1"="SG"]->.sg;
    (
      node["shop"="mall"](area.sg);
      way ["shop"="mall"](area.sg);
      rel ["shop"="mall"](area.sg);
    );
    out center;
    """

    elements = query_overpass(query)
    rows = []

    for el in elements:
        tags = el.get("tags", {})
        name = tags.get("name", "Unknown Mall")
        lat, lon = get_coordinates(el)

        if lat and lon:
            rows.append({"mall_name": name, "lat": lat, "long": lon})

    if not rows:
        print("Warning: No shopping malls found")
        return pd.DataFrame(columns=["mall_name", "lat", "long"])

    df = (pd.DataFrame(rows)
          .drop_duplicates("mall_name")
          .sort_values("mall_name")
          .reset_index(drop=True))

    print(f"Found {len(df)} shopping malls")
    return df


def get_bus_stations() -> pd.DataFrame:
    """
    Query OpenStreetMap for bus stops and bus interchanges in Singapore.

    Only includes stops with official bus stop codes (ref tag).
    This filters out private transport like zoo trams, tourist shuttles, etc.

    Singapore has:
    - Bus interchanges (amenity=bus_station)
    - Regular bus stops (highway=bus_stop) with 5-digit codes

    Returns
    -------
    pd.DataFrame with columns: stop_name, stop_code, type, lat, long
    """
    print("Fetching bus stops and interchanges...")

    query = """
    [out:json][timeout:90];
    area["ISO3166-1"="SG"]->.sg;
    (
      node["amenity"="bus_station"](area.sg);
      way ["amenity"="bus_station"](area.sg);
      rel ["amenity"="bus_station"](area.sg);
      node["highway"="bus_stop"]["ref"](area.sg);
      node["public_transport"="stop_position"]["bus"="yes"]["ref"](area.sg);
      node["public_transport"="platform"]["bus"="yes"]["ref"](area.sg);
    );
    out center;
    """

    elements = query_overpass(query)
    rows = []
    seen_locations = set()

    for el in elements:
        tags = el.get("tags", {})
        name = tags.get("name", "")
        ref = tags.get("ref", "")  # Bus stop code (e.g., "01012")

        # For bus interchanges, ref might not be present but name should indicate it's an interchange
        amenity = tags.get("amenity", "")
        is_interchange = amenity == "bus_station" or "interchange" in name.lower() or "int" in name.lower()

        # CRITICAL: Skip stops without bus stop codes UNLESS it's a bus interchange
        if not ref and not is_interchange:
            continue

        # Skip stops that are clearly not public bus stops (zoo, sentosa, etc.)
        operator = tags.get("operator", "").lower()
        network = tags.get("network", "").lower()
        if any(keyword in operator or keyword in network for keyword in
               ["zoo", "sentosa", "wildlife", "night safari", "tourist"]):
            continue

        # Create a display name
        if name and ref:
            display_name = f"{name} ({ref})"
            stop_code = ref
        elif name:
            display_name = name
            stop_code = ref if ref else "N/A"
        elif ref:
            display_name = f"Bus Stop {ref}"
            stop_code = ref
        else:
            # Should not reach here due to the filter above
            continue

        # Determine type
        if is_interchange:
            stop_type = "Bus Interchange"
        else:
            stop_type = "Bus Stop"

        lat, lon = get_coordinates(el)

        if lat and lon:
            # Use lat/lon to deduplicate (same physical location)
            location_key = f"{lat:.6f},{lon:.6f}"
            if location_key in seen_locations:
                continue
            seen_locations.add(location_key)

            rows.append({
                "stop_name": display_name,
                "stop_code": stop_code,
                "type": stop_type,
                "lat": lat,
                "long": lon
            })

    if not rows:
        print("Warning: No bus stops found")
        return pd.DataFrame(columns=["stop_name", "stop_code", "type", "lat", "long"])

    df = (pd.DataFrame(rows)
          .drop_duplicates("stop_name")
          .sort_values("stop_name")
          .reset_index(drop=True))

    print(f"Found {len(df)} bus stops/interchanges")
    return df


def get_hawker_centres() -> pd.DataFrame:
    """
    Query OpenStreetMap for hawker centres in Singapore.

    Uses a simplified but comprehensive approach to find hawker centres.
    Based on NEA list patterns: most hawker centres have "Food Centre", "Hawker",
    or "Market" in their names.

    Returns
    -------
    pd.DataFrame with columns: hawker_name, lat, long
    """
    print("Fetching hawker centres...")

    # Simplified query - much faster, less likely to timeout
    query = """
    [out:json][timeout:60];
    area["ISO3166-1"="SG"]->.sg;
    (
      node["amenity"="food_court"](area.sg);
      way ["amenity"="food_court"](area.sg);
      rel ["amenity"="food_court"](area.sg);
      node["amenity"="marketplace"](area.sg);
      way ["amenity"="marketplace"](area.sg);
      rel ["amenity"="marketplace"](area.sg);
    );
    out center;
    """

    elements = query_overpass(query)
    print(f"DEBUG: Received {len(elements)} elements from OpenStreetMap")

    rows = []
    seen_names = set()

    for el in elements:
        tags = el.get("tags", {})
        name = tags.get("name", "")

        # Skip if no name
        if not name or name == "Unknown":
            continue

        name_lower = name.lower().strip()

        # POSITIVE matching - include if it has hawker/food centre keywords
        hawker_keywords = ["hawker", "food centre", "food center", "cooked food"]
        has_hawker_keyword = any(keyword in name_lower for keyword in hawker_keywords)

        # Check tags
        is_food_court = tags.get("amenity") == "food_court"
        is_hawker_tagged = tags.get("food_court") == "hawker_centre"

        # NEGATIVE matching - exclude obvious non-hawkers
        exclude_keywords = [
            "ntuc", "fairprice", "cold storage", "giant", "sheng siong",  # Supermarkets
            "courts", "best denki", "harvey norman",  # Retail stores
            "mall", "shopping", "plaza"  # Shopping centers (unless has hawker keyword)
        ]
        has_exclude_keyword = any(keyword in name_lower for keyword in exclude_keywords)

        # Decision logic
        should_include = False

        if is_hawker_tagged:
            # Explicitly tagged as hawker centre - always include
            should_include = True
        elif has_hawker_keyword:
            # Has hawker/food centre in name - include unless it's a shopping mall
            if not has_exclude_keyword:
                should_include = True
        elif is_food_court:
            # Tagged as food court - include if it looks like a hawker (has market/centre/complex in name)
            market_indicators = ["market", "centre", "center", "complex", "blk", "block"]
            if any(indicator in name_lower for indicator in market_indicators):
                should_include = True

        if not should_include:
            continue

        # Skip duplicates
        if name_lower in seen_names:
            continue
        seen_names.add(name_lower)

        lat, lon = get_coordinates(el)

        if lat and lon:
            rows.append({"hawker_name": name, "lat": lat, "long": lon})

    print(f"DEBUG: Filtered to {len(rows)} hawker centres after processing")

    if not rows:
        print("Warning: No hawker centres found in OpenStreetMap")
        print("This likely means OSM has very limited hawker centre data for Singapore.")
        return pd.DataFrame(columns=["hawker_name", "lat", "long"])

    df = (pd.DataFrame(rows)
          .drop_duplicates("hawker_name")
          .sort_values("hawker_name")
          .reset_index(drop=True))

    print(f"Found {len(df)} hawker centres")

    if len(df) < 80:
        print(f"Note: Found {len(df)} hawker centres. Singapore has ~123 official hawker centres.")
        print("OpenStreetMap appears to have incomplete hawker centre coverage.")

    return df

def get_wet_markets() -> pd.DataFrame:
    """
    Query OpenStreetMap for wet markets in Singapore.
    Wet markets sell fresh produce, meat, fish, and groceries.
    Separate from hawker centres which focus on cooked food.

    Returns
    -------
    pd.DataFrame with columns: market_name, lat, long
    """
    print("Fetching wet markets...")

    query = """
    [out:json][timeout:60];
    area["ISO3166-1"="SG"]->.sg;
    (
      node["amenity"="marketplace"](area.sg);
      way ["amenity"="marketplace"](area.sg);
      rel ["amenity"="marketplace"](area.sg);
      node["shop"="marketplace"](area.sg);
      way ["shop"="marketplace"](area.sg);
      rel ["shop"="marketplace"](area.sg);
    );
    out center;
    """

    elements = query_overpass(query)
    rows = []
    seen_names = set()

    for el in elements:
        tags = el.get("tags", {})
        name = tags.get("name", "")

        if not name:
            continue

        # Skip if it's actually a hawker centre or food centre
        name_lower = name.lower()
        if "hawker" in name_lower or "food centre" in name_lower or "food center" in name_lower:
            continue
        if tags.get("amenity") == "food_court":
            continue
        if tags.get("food_court") == "hawker_centre":
            continue

        # Skip duplicates
        if name_lower in seen_names:
            continue
        seen_names.add(name_lower)

        lat, lon = get_coordinates(el)

        if lat and lon:
            rows.append({"market_name": name, "lat": lat, "long": lon})

    if not rows:
        print("Warning: No wet markets found")
        return pd.DataFrame(columns=["market_name", "lat", "long"])

    df = (pd.DataFrame(rows)
          .drop_duplicates("market_name")
          .sort_values("market_name")
          .reset_index(drop=True))

    print(f"Found {len(df)} wet markets")
    return df


def get_schools() -> pd.DataFrame:
    """
    Query OpenStreetMap for schools in Singapore.
    Includes primary, secondary, junior colleges, and universities.

    Returns
    -------
    pd.DataFrame with columns: school_name, school_type, lat, long
    """
    print("Fetching schools...")

    query = """
    [out:json][timeout:60];
    area["ISO3166-1"="SG"]->.sg;
    (
      node["amenity"="school"](area.sg);
      way ["amenity"="school"](area.sg);
      rel ["amenity"="school"](area.sg);
      node["amenity"="college"](area.sg);
      way ["amenity"="college"](area.sg);
      rel ["amenity"="college"](area.sg);
      node["amenity"="university"](area.sg);
      way ["amenity"="university"](area.sg);
      rel ["amenity"="university"](area.sg);
    );
    out center;
    """

    elements = query_overpass(query)
    rows = []

    for el in elements:
        tags = el.get("tags", {})
        name = tags.get("name", "Unknown School")
        amenity = tags.get("amenity", "school")

        # Map amenity type to more readable school type
        school_type_map = {
            "school": "School",
            "college": "College/JC",
            "university": "University"
        }
        school_type = school_type_map.get(amenity, "School")

        lat, lon = get_coordinates(el)

        if lat and lon:
            rows.append({
                "school_name": name,
                "school_type": school_type,
                "lat": lat,
                "long": lon
            })

    if not rows:
        print("Warning: No schools found")
        return pd.DataFrame(columns=["school_name", "school_type", "lat", "long"])

    df = (pd.DataFrame(rows)
          .drop_duplicates("school_name")
          .sort_values("school_name")
          .reset_index(drop=True))

    print(f"Found {len(df)} schools")
    return df


def main():
    """
    Main function to fetch all location data and save to CSV files.
    """
    print("=" * 60)
    print("Fetching Singapore Location Data from OpenStreetMap")
    print("=" * 60)
    print()

    #Fetch all data with delays between requests to be respectful to the API
    mrt_df = get_mrt_stations()
    time.sleep(2)

    malls_df = get_shopping_malls()
    time.sleep(2)

    bus_df = get_bus_stations()
    time.sleep(2)

    hawker_df = get_hawker_centres()
    time.sleep(2)

    markets_df = get_wet_markets()
    time.sleep(2)

    schools_df = get_schools()

    print()
    print("=" * 60)
    print("Saving data to CSV files...")
    print("=" * 60)

    # Save to CSV files
    mrt_df.to_csv("Data/mrt_stations.csv", index=False)
    print(f"mrt_stations.csv ({len(mrt_df)} records)")

    malls_df.to_csv("Data/shopping_malls.csv", index=False)
    print(f"shopping_malls.csv ({len(malls_df)} records)")

    bus_df.to_csv("Data/bus_stops.csv", index=False)
    print(f"bus_stops.csv ({len(bus_df)} records)")

    hawker_df.to_csv("Data/hawker_centres.csv", index=False)
    print(f"hawker_centres.csv ({len(hawker_df)} records)")

    markets_df.to_csv("Data/wet_markets.csv", index=False)
    print(f"wet_markets.csv ({len(markets_df)} records)")

    schools_df.to_csv("Data/schools.csv", index=False)
    print(f"schools.csv ({len(schools_df)} records)")

    print()
    print("=" * 60)
    print("Summary")
    print("=" * 60)
    print(f"Total locations fetched: {len(mrt_df) + len(malls_df) + len(bus_df) + len(hawker_df) + len(markets_df) + len(schools_df)}")
    print()
    print("All CSV files have been saved successfully!")


if __name__ == "__main__":
    main()