# -*- coding: utf-8 -*-
"""Assignment 1 (Lat, Long).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12K9NeHd48fzdINhJGIgnme3DYXQrS7Qy

#Convert Street name, Blk to Lat long
"""

import pandas as pd
import requests
import json
import time

# 1. Load the CSV, i use test.csv(a small version of the ResaleData to test)
file_path = 'Data/ResaleflatpricesbasedonregistrationdatefromJan2017onwards.csv'
df = pd.read_csv(file_path)

# 2. Extract unique addresses (Block + Street Name)
df['address'] = df['block'] + " " + df['street_name']
unique_addresses = df['address'].unique().tolist()
print(f"Total rows in dataset: {len(df)}")
print(f"Total unique addresses to geocode: {len(unique_addresses)}")

# 3. Geocoding Function using OneMap API
def get_coordinates(address_list):
    address_data = []
    url = "https://www.onemap.gov.sg/api/common/elastic/search?searchVal={}&returnGeom=Y&getAddrDetails=Y&pageNum=1"

    print("Starting geocoding... (Based on your internet connection, this may take a while)")

    for i, search_name in enumerate(address_list):
        try:
            response = requests.get(url.format(search_name))
            data = json.loads(response.content)

            if data["found"] != 0:
                result = data["results"][0]
                address_data.append({
                    "address": search_name,
                    "latitude": result["LATITUDE"],
                    "longitude": result["LONGITUDE"],
                })
            else:
                address_data.append({
                    "address": search_name,
                    "latitude": "NotFound",
                    "longitude": "NotFound",
                })
        except Exception as e:
            print(f"Error at {search_name}: {e}")
            address_data.append({"address": search_name, "latitude": "Error", "longitude": "Error"})

        # Progress update every 100 addresses
        if (i + 1) % 100 == 0:
            print(f"Processed {i + 1}/{len(address_list)}...")
            # Optional: Save progress to a temporary CSV
            pd.DataFrame(address_data).to_csv('Data/coords_backup.csv', index=False)

    return pd.DataFrame(address_data)

# 4. Run the Geocoding
# Note: For testing, you can use unique_addresses[:10]
coords_df = get_coordinates(unique_addresses)

# 5. Merge coordinates back to the original Resale Flat data
final_df = df.merge(coords_df, on='address', how='left')


# 6. Save the final enriched dataset
final_df.to_csv('Data/Resale_with_Coords.csv', index=False)
print("Success! Final file saved as 'Resale_with_Coords.csv'")

test = pd.read_csv('Data/Resale_with_Coords.csv')
test.head()